import { CoreGameComponent, type Campaign } from '$lib/core/campaign'
import { armitagesFate } from './encounter'
import { transitions } from './transition'

export const theDunwichLegacyCampaign: Campaign = {
	name: 'The Dunwich Legacy',
	scenarioTransitions: transitions,
	commonEncounterSets: [armitagesFate],
	startingChaosBag: {
		easy: [
			CoreGameComponent.TokenP1,
			CoreGameComponent.TokenP1,
			CoreGameComponent.Token0,
			CoreGameComponent.Token0,
			CoreGameComponent.Token0,
			CoreGameComponent.TokenM1,
			CoreGameComponent.TokenM1,
			CoreGameComponent.TokenM1,
			CoreGameComponent.TokenM2,
			CoreGameComponent.TokenM2,
			CoreGameComponent.TokenSkull,
			CoreGameComponent.TokenSkull,
			CoreGameComponent.TokenCultist,
			CoreGameComponent.TokenAutofail,
			CoreGameComponent.TokenElderSign,
		],
		standard: [
			CoreGameComponent.TokenP1,
			CoreGameComponent.Token0,
			CoreGameComponent.Token0,
			CoreGameComponent.TokenM1,
			CoreGameComponent.TokenM1,
			CoreGameComponent.TokenM1,
			CoreGameComponent.TokenM2,
			CoreGameComponent.TokenM2,
			CoreGameComponent.TokenM3,
			CoreGameComponent.TokenM4,
			CoreGameComponent.TokenSkull,
			CoreGameComponent.TokenSkull,
			CoreGameComponent.TokenCultist,
			CoreGameComponent.TokenAutofail,
			CoreGameComponent.TokenElderSign,
		],
		hard: [
			CoreGameComponent.Token0,
			CoreGameComponent.Token0,
			CoreGameComponent.Token0,
			CoreGameComponent.TokenM1,
			CoreGameComponent.TokenM1,
			CoreGameComponent.TokenM2,
			CoreGameComponent.TokenM2,
			CoreGameComponent.TokenM3,
			CoreGameComponent.TokenM3,
			CoreGameComponent.TokenM4,
			CoreGameComponent.TokenM5,
			CoreGameComponent.TokenSkull,
			CoreGameComponent.TokenSkull,
			CoreGameComponent.TokenCultist,
			CoreGameComponent.TokenAutofail,
			CoreGameComponent.TokenElderSign,
		],
		expert: [
			CoreGameComponent.Token0,
			CoreGameComponent.TokenM1,
			CoreGameComponent.TokenM1,
			CoreGameComponent.TokenM2,
			CoreGameComponent.TokenM2,
			CoreGameComponent.TokenM3,
			CoreGameComponent.TokenM3,
			CoreGameComponent.TokenM4,
			CoreGameComponent.TokenM4,
			CoreGameComponent.TokenM5,
			CoreGameComponent.TokenM6,
			CoreGameComponent.TokenM8,
			CoreGameComponent.TokenSkull,
			CoreGameComponent.TokenSkull,
			CoreGameComponent.TokenCultist,
			CoreGameComponent.TokenAutofail,
			CoreGameComponent.TokenElderSign,
		],
	},
}
