import { GameComponent, type Campaign } from '$lib/core/campaign'
import { CardPack } from '$lib/core/card-pack'
import {
	aPhantomOfTruthScenario,
	blackStarsRiseScenario,
	curtainCallScenario,
	dimCarcosaScenario,
	echoesOfThePastScenario,
	returnToAPhantomOfTruthScenario,
	returnToBlackStarsRiseScenario,
	returnToCurtainCallScenario,
	returnToDimCarcosaScenario,
	returnToEchoesOfThePastScenario,
	returnToTheLastKingScenario,
	returnToThePallidMaskScenario, returnToTheUnspeakableOathScenario,
	theLastKingScenario,
	thePallidMaskScenario,
	theUnspeakableOathScenario
} from '$lib/campaign/ptc/scenario'

export const thePathToCarcosaCampaign: Campaign = {
	name: 'The Path to Carcosa',
	investigatorExpansion: CardPack.ThePathToCarcosa,
	scenarios:[
		aPhantomOfTruthScenario,
		blackStarsRiseScenario,
		curtainCallScenario,
		dimCarcosaScenario,
		echoesOfThePastScenario,
		theLastKingScenario,
		thePallidMaskScenario,
		theUnspeakableOathScenario,
	],
	startingChaosBag: {
		easy: [
			GameComponent.TokenP1,
			GameComponent.TokenP1,
			GameComponent.Token0,
			GameComponent.Token0,
			GameComponent.Token0,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM2,
			GameComponent.TokenM2,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenAutofail,
			GameComponent.TokenElderSign,
		],
		standard: [
			GameComponent.TokenP1,
			GameComponent.Token0,
			GameComponent.Token0,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM2,
			GameComponent.TokenM2,
			GameComponent.TokenM3,
			GameComponent.TokenM4,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenAutofail,
			GameComponent.TokenElderSign,
		],
		hard: [
			GameComponent.Token0,
			GameComponent.Token0,
			GameComponent.Token0,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM2,
			GameComponent.TokenM2,
			GameComponent.TokenM3,
			GameComponent.TokenM4,
			GameComponent.TokenM5,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenAutofail,
			GameComponent.TokenElderSign,
		],
		expert: [
			GameComponent.Token0,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM2,
			GameComponent.TokenM2,
			GameComponent.TokenM3,
			GameComponent.TokenM3,
			GameComponent.TokenM4,
			GameComponent.TokenM4,
			GameComponent.TokenM5,
			GameComponent.TokenM6,
			GameComponent.TokenM8,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenAutofail,
			GameComponent.TokenElderSign,
		],
	},
}

export const returnToThePathToCarcosaCampaign: Campaign = {
	name: 'Return to the Path to Carcosa',
	investigatorExpansion: CardPack.ReturnToThePathToCarcosa,
	scenarios:[
		returnToAPhantomOfTruthScenario,
		returnToBlackStarsRiseScenario,
		returnToCurtainCallScenario,
		returnToDimCarcosaScenario,
		returnToEchoesOfThePastScenario,
		returnToTheLastKingScenario,
		returnToThePallidMaskScenario,
		returnToTheUnspeakableOathScenario,
	],
	commonEncounterSets: [],
	startingChaosBag: {
		easy: [],
		standard: [],
		hard: [],
		expert: [],
	},
}
