import {
	cityOfTheElderThings1Scenario,
	cityOfTheElderThings2Scenario,
	cityOfTheElderThings3Scenario,
	fatalMirageScenario,
	iceAndDeathPart1Scenario,
	iceAndDeathPart2Scenario,
	iceAndDeathPart3Scenario,
	theHeartOfMadness1Scenario,
	theHeartOfMadness2Scenario,
	toTheForbiddenPeaksScenario,
} from '$lib/campaign/eote/scenario'
import { type Campaign, GameComponent } from '$lib/core/campaign'
import { CardPack } from '$lib/core/card-pack'

import { expeditionTeam, memorialsOfTheLost, tekelili } from './encounter'

export const edgeOfTheEarthCampaign: Campaign = {
	name: 'Edge of the Earth',
	investigatorExpansion: CardPack.EdgeOfTheEarth,
	setupReferenceGraphic:
		'https://drive.google.com/drive/folders/1QhOJKCkikhDpM1c2oLjyzC4celG0umam?usp=share_link',
	scenarios: [
		cityOfTheElderThings1Scenario,
		cityOfTheElderThings2Scenario,
		cityOfTheElderThings3Scenario,
		fatalMirageScenario,
		iceAndDeathPart1Scenario,
		iceAndDeathPart2Scenario,
		iceAndDeathPart3Scenario,
		theHeartOfMadness1Scenario,
		theHeartOfMadness2Scenario,
		toTheForbiddenPeaksScenario,
	],
	commonEncounterSets: [tekelili, expeditionTeam, memorialsOfTheLost],
	startingChaosBag: {
		easy: [
			GameComponent.TokenP1,
			GameComponent.TokenP1,
			GameComponent.TokenP1,
			GameComponent.Token0,
			GameComponent.Token0,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM2,
			GameComponent.TokenM2,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenCultist,
			GameComponent.TokenTablet,
			GameComponent.TokenAutofail,
			GameComponent.TokenElderSign,
		],
		standard: [
			GameComponent.TokenP1,
			GameComponent.Token0,
			GameComponent.Token0,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM2,
			GameComponent.TokenM2,
			GameComponent.TokenM3,
			GameComponent.TokenM4,
			GameComponent.TokenFrost,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenCultist,
			GameComponent.TokenTablet,
			GameComponent.TokenAutofail,
			GameComponent.TokenElderSign,
		],
		hard: [
			GameComponent.Token0,
			GameComponent.Token0,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM2,
			GameComponent.TokenM2,
			GameComponent.TokenM3,
			GameComponent.TokenM4,
			GameComponent.TokenM4,
			GameComponent.TokenM5,
			GameComponent.TokenFrost,
			GameComponent.TokenFrost,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenCultist,
			GameComponent.TokenTablet,
			GameComponent.TokenAutofail,
			GameComponent.TokenElderSign,
		],
		expert: [
			GameComponent.Token0,
			GameComponent.TokenM1,
			GameComponent.TokenM2,
			GameComponent.TokenM2,
			GameComponent.TokenM3,
			GameComponent.TokenM4,
			GameComponent.TokenM4,
			GameComponent.TokenM5,
			GameComponent.TokenM7,
			GameComponent.TokenFrost,
			GameComponent.TokenFrost,
			GameComponent.TokenFrost,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenCultist,
			GameComponent.TokenTablet,
			GameComponent.TokenAutofail,
			GameComponent.TokenElderSign,
		],
	},
}
