export const allIcons = {
	rightSingle: ic('angle-right-duotone'),
	rightDouble: ic('angles-right-duotone'),
	arrowUp: ic('arrow-up-solid'),
	arrowUpAdd: ic('arrow-up-add-solid'),
	arrowDown: ic('arrow-down-solid'),
	arrowDownAdd: ic('arrow-down-add-solid'),
	arrowLeftBordered: ic('left-regular'),
	arrowRightBordered: ic('right-regular'),
	delete: ic('trash-regular'),
	unlock: ic('lock-open-regular'),
	collapse: ic('arrows-to-line-regular'),
	investigatorRestriction: ic('user-lock-solid'),
	noticeInfo: ic('circle-info-solid'),
	noticeSuccess: ic('circle-check-solid'),
	noticeError: ic('circle-exclamation-solid'),
	loading: ic('spinner-third-duotone'),
	manual: ic('book-solid'),
	plus: ic('plus-solid'),
	minus: ic('minus-solid'),
	grip: ic('grip-dots-vertical-regular'),
	customizable: ic('wrench-solid'),
	bonded: ic('link-solid'),
	exceptional: ic('star-regular'),
	permanent: ic('brick-wall'),
	checkBox: ic('square-regular'),
	checkBoxChecked: ic('square-check-regular'),
	investigator: ic('user-solid'),
	expand: ic('arrow-up-right-and-arrow-down-left-from-center-regular'),
	weakness: ic('weakness'),
	anyWeakness: ic('virus-solid'),
	experience: ic('arrow-up-right-dots-solid'),
	myraid: ic('layer-group-solid'),
}

function ic(s: string): string {
	return '/fa/' + s + '.svg'
}
