export enum ChaosToken {
  Plus1 = "+1",
  Zero = "0",
  Minus1 = "-1",
  Minus2 = "-2",
  Minus3 = "-3",
  Minus4 = "-4",
  Minus5 = "-5",
  Minus6 = "-6",
  Minus7 = "-7",
  Minus8 = "-8",
  Skull = "Skull",
  Cultist = "Cultist",
  Tablet = "Tablet",
  ElderThing = "ElderThing",
  AutoFail = "Autofail",
  ElderSign = "ElderSign",
  Frost = "Frost",
}
