import { type Campaign, GameComponent } from '$lib/core/campaign'
import { CardPack } from '$lib/core/card-pack'

import { armitagesFate } from './encounter'
import {
	bloodOnTheAltarScenario,
	extracurricularActivityScenario,
	lostInTimeAndSpaceScenario,
	returnToBloodOnTheAltarScenario,
	returnToExtracurricularActivityScenario,
	returnToLostInTimeAndSpaceScenario,
	returnToTheEssexCountyExpressScenario,
	returnToTheHouseAlwaysWinsScenario,
	returnToTheMiskatonicMuseumScenario,
	returnToUndimensionedAndUnseenScenario,
	returnToWhereDoomAwaitsScenario,
	theEssexCountyExpressScenario,
	theHouseAlwaysWinsScenario,
	theMiskatonicMuseumScenario,
	undimensionedAndUnseenScenario,
	whereDoomAwaitsScenario,
} from './scenario'

export const theDunwichLegacyCampaign: Campaign = {
	name: 'The Dunwich Legacy',
	investigatorExpansion: CardPack.TheDunwichLegacy,
	setupReferenceGraphic:
		'https://drive.google.com/drive/folders/11w8AtIlhDIhuxCdKdz1YKAxDCut4s5hz?usp=share_link',
	scenarios: [
		bloodOnTheAltarScenario,
		extracurricularActivityScenario,
		lostInTimeAndSpaceScenario,
		theEssexCountyExpressScenario,
		theHouseAlwaysWinsScenario,
		theMiskatonicMuseumScenario,
		undimensionedAndUnseenScenario,
		whereDoomAwaitsScenario,
	],
	commonEncounterSets: [armitagesFate],
	startingChaosBag: {
		easy: [
			GameComponent.TokenP1,
			GameComponent.TokenP1,
			GameComponent.Token0,
			GameComponent.Token0,
			GameComponent.Token0,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM2,
			GameComponent.TokenM2,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenCultist,
			GameComponent.TokenAutofail,
			GameComponent.TokenElderSign,
		],
		standard: [
			GameComponent.TokenP1,
			GameComponent.Token0,
			GameComponent.Token0,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM2,
			GameComponent.TokenM2,
			GameComponent.TokenM3,
			GameComponent.TokenM4,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenCultist,
			GameComponent.TokenAutofail,
			GameComponent.TokenElderSign,
		],
		hard: [
			GameComponent.Token0,
			GameComponent.Token0,
			GameComponent.Token0,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM2,
			GameComponent.TokenM2,
			GameComponent.TokenM3,
			GameComponent.TokenM3,
			GameComponent.TokenM4,
			GameComponent.TokenM5,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenCultist,
			GameComponent.TokenAutofail,
			GameComponent.TokenElderSign,
		],
		expert: [
			GameComponent.Token0,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM2,
			GameComponent.TokenM2,
			GameComponent.TokenM3,
			GameComponent.TokenM3,
			GameComponent.TokenM4,
			GameComponent.TokenM4,
			GameComponent.TokenM5,
			GameComponent.TokenM6,
			GameComponent.TokenM8,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenCultist,
			GameComponent.TokenAutofail,
			GameComponent.TokenElderSign,
		],
	},
}

export const returnToTheDunwichLegacyCampaign: Campaign = {
	name: 'Return to the Dunwich Legacy',
	investigatorExpansion: CardPack.ReturnToTheDunwichLegacy,
	setupReferenceGraphic:
		'https://drive.google.com/drive/folders/1r3Cn1tj23-CKKSGxTpypeat5rKzg6Zn0?usp=share_link',
	scenarios: [
		returnToBloodOnTheAltarScenario,
		returnToExtracurricularActivityScenario,
		returnToLostInTimeAndSpaceScenario,
		returnToTheEssexCountyExpressScenario,
		returnToTheHouseAlwaysWinsScenario,
		returnToTheMiskatonicMuseumScenario,
		returnToUndimensionedAndUnseenScenario,
		returnToWhereDoomAwaitsScenario,
	],
	commonEncounterSets: [armitagesFate],
	startingChaosBag: {
		easy: [
			GameComponent.TokenP1,
			GameComponent.TokenP1,
			GameComponent.Token0,
			GameComponent.Token0,
			GameComponent.Token0,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM2,
			GameComponent.TokenM2,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenCultist,
			GameComponent.TokenAutofail,
			GameComponent.TokenElderSign,
		],
		standard: [
			GameComponent.TokenP1,
			GameComponent.Token0,
			GameComponent.Token0,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM2,
			GameComponent.TokenM2,
			GameComponent.TokenM3,
			GameComponent.TokenM4,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenCultist,
			GameComponent.TokenAutofail,
			GameComponent.TokenElderSign,
		],
		hard: [
			GameComponent.Token0,
			GameComponent.Token0,
			GameComponent.Token0,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM2,
			GameComponent.TokenM2,
			GameComponent.TokenM3,
			GameComponent.TokenM3,
			GameComponent.TokenM4,
			GameComponent.TokenM5,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenCultist,
			GameComponent.TokenAutofail,
			GameComponent.TokenElderSign,
		],
		expert: [
			GameComponent.Token0,
			GameComponent.TokenM1,
			GameComponent.TokenM1,
			GameComponent.TokenM2,
			GameComponent.TokenM2,
			GameComponent.TokenM3,
			GameComponent.TokenM3,
			GameComponent.TokenM4,
			GameComponent.TokenM4,
			GameComponent.TokenM5,
			GameComponent.TokenM6,
			GameComponent.TokenM8,
			GameComponent.TokenSkull,
			GameComponent.TokenSkull,
			GameComponent.TokenCultist,
			GameComponent.TokenAutofail,
			GameComponent.TokenElderSign,
		],
	},
}
